[features]
seeds = false

[programs.localnet]
tohken = "5xn4f5XvFNjXfoWu4Twdq9LBGN9GgCg2cKyPuYJRiTEV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/aaron/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
